-- CreatorKeyword Pro - Supabase Migration Schema
-- Run this in your Supabase SQL Editor to enable Cloud Sync and Auth

-- 1. Profiles Table (Linked to Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  credits INTEGER DEFAULT 30,
  plan TEXT DEFAULT 'starter',
  preferred_language TEXT DEFAULT 'English',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own profile" 
ON public.profiles FOR SELECT 
USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile" 
ON public.profiles FOR UPDATE 
USING (auth.uid() = id);

-- 2. Saved Keywords Table
CREATE TABLE IF NOT EXISTS public.saved_keywords (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  keyword TEXT NOT NULL,
  search_volume INTEGER DEFAULT 0,
  competition_score INTEGER DEFAULT 0,
  cpc_value DECIMAL DEFAULT 0.00,
  intent_type TEXT,
  trend_direction TEXT,
  strategy TEXT,
  cluster TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on saved_keywords
ALTER TABLE public.saved_keywords ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own saved keywords" 
ON public.saved_keywords FOR ALL 
USING (auth.uid() = user_id);

-- 3. Content Projects Table
CREATE TABLE IF NOT EXISTS public.content_projects (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  keyword TEXT NOT NULL,
  brief TEXT,
  draft TEXT,
  format TEXT DEFAULT 'blog',
  status TEXT DEFAULT 'draft',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on content_projects
ALTER TABLE public.content_projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own projects" 
ON public.content_projects FOR ALL 
USING (auth.uid() = user_id);

-- 4. Search History Table
CREATE TABLE IF NOT EXISTS public.search_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  query TEXT NOT NULL,
  mode TEXT NOT NULL,
  results JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on search_history
ALTER TABLE public.search_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own search history" 
ON public.search_history FOR ALL 
USING (auth.uid() = user_id);

-- 5. Auth Trigger (Auto-create profile on signup)
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, credits, plan)
  VALUES (NEW.id, NEW.email, 30, 'starter');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
