import { Client } from '@notionhq/client';
import { NextResponse } from 'next/server';

export async function POST(req: Request) {
    try {
        const { title, brief, draft, format } = await req.json();

        const notionKey = process.env.NOTION_API_KEY;
        const parentPageId = process.env.NOTION_PARENT_PAGE_ID;

        if (!notionKey || !parentPageId) {
            return NextResponse.json({
                error: 'Notion integration not configured. Please add NOTION_API_KEY and NOTION_PARENT_PAGE_ID to your environment.'
            }, { status: 400 });
        }

        const notion = new Client({ auth: notionKey });

        // Helper to split text into chunks of 2000 chars for Notion
        const toBlocks = (text: string) => {
            if (!text) return [];
            const chunks = text.match(/[\s\S]{1,2000}/g) || [];
            return chunks.map(chunk => ({
                object: 'block',
                type: 'paragraph',
                paragraph: {
                    rich_text: [{ type: 'text', text: { content: chunk } }],
                },
            }));
        };

        const response = await notion.pages.create({
            parent: { page_id: parentPageId },
            properties: {
                title: {
                    title: [
                        {
                            text: {
                                content: `🎯 ${title}`,
                            },
                        },
                    ],
                },
            },
            children: [
                {
                    object: 'block',
                    type: 'heading_2',
                    heading_2: {
                        rich_text: [{ type: 'text', text: { content: 'Strategic Brief' } }],
                    },
                },
                ...(toBlocks(brief) as any),
                {
                    object: 'block',
                    type: 'heading_2',
                    heading_2: {
                        rich_text: [{ type: 'text', text: { content: 'Generated Draft' } }],
                    },
                },
                ...(toBlocks(draft) as any),
                {
                    object: 'block',
                    type: 'divider',
                    divider: {}
                },
                {
                    object: 'block',
                    type: 'paragraph',
                    paragraph: {
                        rich_text: [{
                            type: 'text',
                            text: { content: `Generated by Stitch Creator Intelligence • ${new Date().toLocaleDateString()}` },
                            annotations: { italic: true, id: 'footer-text' }
                        }],
                    },
                },
            ],
        });

        return NextResponse.json({ success: true, url: (response as any).url });
    } catch (error: any) {
        console.error('[notion] Error:', error.message);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
